language: node_js
node_js:
  - "12.13.0"

install:
  - cd test
  - npm ci


matrix:
  include:
    - name: "Linux Test"
      os: linux
      if: NOT commit_message =~ /^:hammer:/
      dist: xenial
      sudo: false
      script:
        - echo OK.
      # before_script:
      #   - export OCL_ICD_FILENAMES=libintelocl.so
      #   - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/node-3d/opencl-raub/ci
      #   - export OCL_ICD_VENDORS=/home/travis/build/node-3d/opencl-raub/ci
    - name: "OSX Test"
      os: osx
      if: NOT commit_message =~ /^:hammer:/
    - name: "Linux Build"
      os: linux
      dist: xenial
      sudo: false
      if: commit_message =~ /^:hammer:/
      env:
        - ISBUILD=true
        - SYSNAME=Linux
      install:
        - cd src
      script:
        - npm ci
    - name: "OSX Build"
      os: osx
      if: commit_message =~ /^:hammer:/
      env:
        - ISBUILD=true
        - SYSNAME=OSX
      install:
        - cd src
      script:
        - npm ci

script:
  - npm test context
  - npm test device
  - npm test event
  - npm test kernel
  - npm test memobj
  - npm test platform
  - npm test program
  - npm test queues
  - npm test queues-buffer
  - npm test queues-image
  - npm test queues-image-copy
  - npm test sampler

deploy:
  on:
    all_branches: true
    condition: $ISBUILD = true
  provider: releases
  name: "Binary for $SYSNAME"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  prerelease: false
  tag_name: "$SYSNAME"
  file:
    - "build/Release/opencl.node"
