name: Test
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    strategy:
        matrix:
          os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Install OpenCL - Ubuntu
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          # download the key to system keyring
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          # add signed entry to apt sources and configure the APT client to use Intel repository:
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt update -qq
          sudo apt install -qq ocl-icd-opencl-dev intel-oneapi-runtime-opencl

      - name: Build Current Binary
        run: npm run build

      - name: Run Unit Tests
        if: matrix.os != 'macos-14'
        run: npm run test-ci

      - name: Run Index Tests - MacOS
        if: matrix.os == 'macos-14'
        run: node index.js
