name: Test
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    strategy:
        matrix:
          os: [ubuntu-22.04, ubuntu-22.04-arm, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Install OpenCL - Ubuntu
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq ocl-icd-opencl-dev pocl-opencl-icd

      - name: Build Current Binary
        run: npm run build

      - name: Run Unit Tests
        run: npm run test-ci
